### ISSUE TITLE
Set default Snapshot Retention

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#10]
We should set a default Retention (i.e. 90 days) if none is set for SnapshotReferences.

The overall goal is to ensure that Metadata never grows indefinitely.
During implementation, if you notice other fields that continue growing, please open separate issues.

**Comment by wobu** [comment]
Please consider the undocumented iceberg table property: https://github.com/apache/iceberg/blob/0eab91aad705205ebbf675eeb9ea49d3a07d4755/core/src/main/java/org/apache/iceberg/TableProperties.java#L330

so when this property is set to true, snapshot retention should be deactivated for this table. 

There are cases where cleanup of snapshots would break read pipelines, e.g. streaming reads of iceberg tables depends on the snapshots and they are used for synchronisation. if they get cleaned up before the depending pipelines have processed them, the pipelines will fail.

**Comment by c-thiel** [comment]
@wobu thanks, will do. Will be part of 0.2.0 Release.
Related to https://github.com/hansetag/iceberg-catalog/issues/150

**Comment by c-thiel** [comment]
For now the catalog does not actively clean Snapshots. Instead, please use Spark expire snapshots routine which is compatible with the catalog.
