### ISSUE TITLE
Test azure integration on ci

### ISSUE THREAD

**Issue by twuebi** [hansetag/iceberg-catalog#230]
- [ ] run `crates/iceberg-catalog/src/service/storage/az.rs:565` on CI
  - this test will run if an env `TEST_AZURE`  is present at compile time, it requires a list of further envs: 
```rust
let account_name = std::env::var("AZURE_STORAGE_ACCOUNT_NAME").unwrap();
let client_id = std::env::var("AZURE_CLIENT_ID").unwrap();
let client_secret = std::env::var("AZURE_CLIENT_SECRET").unwrap();
let tenant_id = std::env::var("AZURE_TENANT_ID").unwrap();
let filesystem = std::env::var("AZURE_STORAGE_FILESYSTEM").unwrap();
```
- [ ] write an integration test using pyspark which runs against az

Some thoughts:

- we need to create some repo secret which is mounted for these jobs
- the secret should be available to workflow runs triggered from outside this repo

**Comment by c-thiel** [comment]
- [ ] While on int, fix Readme to set checkmark for ADLS to done.
