### ISSUE TITLE
Type-safe(r) properties

### ISSUE THREAD

**Issue by twuebi** [hansetag/iceberg-catalog#237]
Currently there are a bunch of `HashMap<String, String>` around which give a lot of potential for errors & make some things fallible that shouldn't be fallible. We should look into making these more type-safe, perhaps by introducing an enum for keys. This may require changes in iceberg-rust as we import most of the offending types from there (Table|ViewMetadata).

**Comment by twuebi** [comment]
Another option would be to write wrappers around the iceberg-rust types, either as traits or as some class wrapper, that would ensure only writing valid data, reading would remain fallible but that would be handled uniformly on the respective type instead of at every location of usage.

**Comment by c-thiel** [comment]
We have some leftovers such as "write.metadata.compression-codec" and "write.data.path" that we should migrate to the iceberg-ext crate
