### ISSUE TITLE
BREAKING CHANGE: Prohibit dots "." in namespace names

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#242]
The servlet spec changed and does not allow the previous namespace separator anymore.
Current consensus in the community is to make the character configurable.

I believe for now the most consistent way is to reserve "." as a separator. Using "." is discouraged in identifier names anyway as they always require escaping in SQL which is error prone.

Related info: 
New canonicalization: https://jakarta.ee/specifications/servlet/6.0/jakarta-servlet-spec-6.0.html#uri-path-canonicalization
Iceberg Issue: https://github.com/apache/iceberg/issues/10338
Iceberg PR: https://github.com/apache/iceberg/pull/10877/files

**Comment by twuebi** [comment]
#257
