### ISSUE TITLE
Improve Tracing & Logging

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#28]
Revisit & Overhaul the logging concept:

- [ ] Implement internal Error class that has into `ErrorModel` implemented: https://github.com/hansetag/iceberg-rest-server/blob/11e7592b8cc517a314c4c9de42e7f49594833d4d/crates/iceberg-ext/src/catalog/rest/error.rs#L56
- [x] All logs should be output as json for easier parsing with Loki
- [ ] Make sure `IcebergErrorResponse` stacks are not returned to clients, but log them once they occur
- [x] Use `tracing` for logs

**Comment by twuebi** [comment]
adding a request id to the logs will also be helpful

**Comment by c-thiel** [comment]
Follow-up: https://github.com/hansetag/iceberg-catalog/issues/81
