### ISSUE TITLE
Only one table per location

### ISSUE THREAD

**Issue by twuebi** [hansetag/iceberg-catalog#321]
We should make it impossible for two tables to live at the same location. If two tables live at the same location, we'll end up handing out credentials for one table that will also work for the other.

Options:

1. add unique constraint to location in tabular db table
2. check before insert
3. both

**Comment by c-thiel** [comment]
Unique constraint won't quite be enough, we also need to make sure no table is created in a parent folder.

As this is an expensive op, I think we should:
1. Ensure Warehouse locations are unique - must not have same key prefix for same filesystem/bucket /endpoint. This allows us to 
2. Use the warehouse_id filter for unique table locations, but we need the prefix search.
3. Additionaly ensure a path is empty on table creation. Might this be sufficient on its own?

**Comment by twuebi** [comment]
solved via #335
