### ISSUE TITLE
Implement OAuth Authentication

### ISSUE THREAD

**Issue by c-thiel** [hansetag/iceberg-catalog#5]
The catalog should behave like an OAuth Application.
Right now the catalog itself does not include built-in Authentication. Instead, users have to valide the `Authorization` Header using additional proxies before the endpoints.

We should add a couple of basic Authentication algorithms into the shipped binary - the most important one being validation for OAuth tokens. This could be added dynamically based on configuration as a `tower::Layer` on `serve`.

**Comment by twuebi** [comment]
@c-thiel this duplicates what we did in #89  for #47?
