### ISSUE TITLE
Revisit error handling

### ISSUE THREAD

**Issue by twuebi** [hansetag/iceberg-catalog#81]
- [x] commit transaction failure can end up as a 500 (https://github.com/hansetag/iceberg-catalog/pull/176)

**Comment by c-thiel** [comment]
- [ ] Implement internal Error class that has into `ErrorModel` implemented: https://github.com/hansetag/iceberg-rest-server/blob/11e7592b8cc517a314c4c9de42e7f49594833d4d/crates/iceberg-ext/src/catalog/rest/error.rs#L56
- [ ] Make sure `IcebergErrorResponse` stacks are not returned to clients, but log them once they occur
